- dev-context/async/comparison-cef-cloudevents.md
Migrated PR https://github.com/otto-ec/ottoapi_guidelines/pull/2119
add kafka binary representation including sequenceKey and sequenceNumber to the "Comparison of Common Event Format to CloudEvents" document
Author: @andrekaplick5678
> Improve "Comparison of Common Event Format to CloudEvents" document

- api-guidelines/async/format/test-extension/rules/may-use-test-extension.md
- dev-context/async/comparison-cef-cloudevents.md
Changelog:
- Adapted test-type in example to match description [R200021](https://api.otto.de/portal/guidelines/r200021).
- Adapted test extension in comparison examples to match API guidelines [R200021](https://api.otto.de/portal/guidelines/r200021).
> fix(examples): adapt test extension in example to match API guidelines

- api-guidelines/rest/compatibility/versioning-of-incompatible-changes/rules/must-use-profiles-for-versioning.md
The rule contains a lot of content and was hard to consume. Therefore added headlines for structure and better orientation.
> docs(structure): include headlines for better structure

- api-guidelines/async/format/test-extension/rules/may-use-test-extension.md
It is proposed to allow custom test types that are not contained in the current list, which is helpful for special tests such as PreGoliveTest or similar.
Changelog:
- Changed test extension of rule [R200021](https://api.otto.de/portal/guidelines/R200021) to allow additional test types.
- Changed the example that did not contain the correct test type.
> fix(docs): change example and allow additional test types

- api-guidelines/global/json/identifiers/rules/should-use-customerid-to-identify-customers.md
- api-guidelines/rest/authorization/oauth/README.md
Changelog:
- Clarified that the `sub` claim of tokens granted through the Authorization Code Grant flow contains the customerId instead of ec-uuid for now, see "SHOULD use customerId to identify customers [R100078](https://api.otto.de/portal/guidelines/r100078)".
> feat(docs): Clarify that the customerId is now in the sub claim

- api-guidelines/global/json/identifiers/rules/should-use-customerid-to-identify-customers.md
Changelog:
- Aligned the customerId header name in rule "SHOULD use customerId to identify customers [R100078](https://api.otto.de/portal/guidelines/r100078)" to follow the deprecation of `X-`prefixes according RFC6648.
> feat(docs): Rename customerId header according to RFC6648

- api-guidelines/global/json/identifiers/rules/should-use-customerid-to-identify-customers.md
- api-guidelines/rest/authorization/oauth/rules/must-use-authorization-grant.md
Changelog:
- Added links to use cases for "MUST use Authorization Grant [R000052](api-guidelines/api-guidelines/rest/authorization/oauth/rules/must-use-authorization-grant.md)".
- Emphasize warning, when not to use customerId as HTTP header for "SHOULD use customerId to identify customers [R100078](api-guidelines/api-guidelines/global/json/identifiers/rules/should-use-customerid-to-identify-customers.md)".
> fix(rule): refine customerId and oauth2 grants

- CONTRIBUTING.md
Relates to [ottoapi_docs otto-ec/ottoapi_orga#91](https://github.com/otto-ec/ottoapi_orga/issues/91)
Adds checklist to review a pull request in the api-guidelines repository.
> docs(checklist): add pr review checklist

- api-guidelines/global/json/canonical-data-types/rules/must-use-common-data-formats.md
Changelog:
- Added uri-list format to rule "MUST use common data formats [R100071](https://api.otto.de/portal/guidelines/r100071)".
> fix(rule): add uri-list to common formats

- api-guidelines/async/concepts/README.md
Changelog:
- Replaced the dead link to `serialized.io/ddd/domain-event` with its internet archive counterpart.
> fix: OTTOAPI-510, Dead Link in Event Guidelines - Domain Events reference

- api-guidelines/global/json/canonical-data-types/rules/must-use-common-data-formats.md
Changelog:
- Fixed the link to the date rule in "MUST use common data formats" [R100071](https://api.otto.de/portal/guidelines/r100071).
> fix(docs): fix linking for date rule

- CONTRIBUTING.md
Adds command to [CONTRIBUTING.md](https://github.com/otto-de/api-guidelines/blob/main/CONTRIBUTING.md) that can be used to determine available rule IDs for new guidelines.
> chore(docs): Update CONTRIBUTING.md

- api-guidelines/async/compatibility/README.md
- api-guidelines/global/compatibility/README.md
- api-guidelines/rest/compatibility/README.md
Fixes https://github.com/otto-ec/techwriting_hub/issues/115 .
Introduced with https://github.com/otto-de/api-guidelines/pull/62/files (readme file has been removed).
> docs(guidelines): fix E2E test by removing broken links

- api-guidelines/global/core-principles/documentation.md
- api-guidelines/global/core-principles/quality-standards.md
**Context**
- Closes [issue 15](https://github.com/otto-ec/techwriting_hub/issues/15)
- Removes accordions to better display the content hidden behind them.
- Uses TOCs to access the different sub-sections.
- Rewrites and trims documentation chapter.
**To reviewers**
- Check if the restructuring helps to better digest and access the provided content.
- Check if rewriting leads to optimization of the chapters.
- Fix any typos or grammar you might find.
- Add anything that you see missing.
> chore(docs): restructure and rewrite content in documentation and quality standards chapters

- api-guidelines/async/semantics/event-structure/rules/must-prepare-consumers-to-consume-events-idempotently.md
- api-guidelines/async/semantics/event-structure/rules/should-send-durable-event-ids.md
Changelog:
- SHOULD send durable event IDs [R000058](https://api.otto.de/portal/guidelines/r000058)
> feat(guidelines): add new rule for sending durable event ids

- api-guidelines/async/semantics/event-structure/rules/should-send-durable-event-ids.md
- api-guidelines/rest/http/headers/rules/must-forward-test-header.md
- changes/changelog.md
**To reviewers:**
I had a look at the failing E2E tests and figured out the following issues:
- fix broken links
- fix duplicated rule Id as R000058 is already used here https://api.otto.de/portal/guidelines/r000058
Somehow there are some changes in lines that I didn't even touch (all changes after 2024-03-06) and there is no visible change as well. I guess it's a GitHub bug :D
> chore(changelog): fix broken and duplicated links

- api-guidelines/async/kafka/topics/rules/must-follow-kafka-topic-naming-convention.md
Changelog:
- Fixed dead link in rule [r200006](portal/guidelines/r200006).
> fix(dead-link): replace link to internal kafka naming conventions r200006

- changes/changelog.md
Removed last entry from public changelog as the change is a chore on docs and not relevant on operational level.
> chore(changelog): remove changelog entry

- api-guidelines/async/contract/asyncapi/rules/must-provide-api-specification-using-asyncapi-for-asyncrhonous-apis.md
Changelog:
- Fixed the links to the AsyncAPI docs in "MUST provide API specification using AsyncAPI for asynchronous APIs" [R200005](https://api.otto.de/portal/guidelines/R200005).
> fix(guidelines): fix links in r200005

- api-guidelines/rest/errors/error-handling/rules/may-add-custom-extensions-by-defining-a-problem-type.md
- api-guidelines/rest/errors/error-handling/rules/must-use-problem-json-as-error-response-format.md
- api-guidelines/rest/errors/error-handling/rules/should-use-existing-problem-types.md
- dev-context/rest/error-responses.md
- src/linting/plugin.ts
- src/linting/rules/operation-4xx-problem-details-rfc9457.spec.ts
- src/linting/rules/operation-4xx-problem-details-rfc9457.ts
RFC7807 has been replaced by RFC9457.
Changelog:
- Referred to RFC 9457 instead of obsoleted RFC 7807 in "MUST use problem+json as error response format [R000034](https://api.otto.de/portal/guidelines/r000034)", "SHOULD use existing problem types [R000037](http://api.otto.de/portal/guidelines/r000037)", and "MAY add custom extensions by defining a problem type [R000040](https://api.otto.de/portal/guidelines/r000040)".
> chore(guidelines): Relate to rfc9457 instead of rfc7807

- dev-context/rest/error-responses.md
Added links to Spring-framework documentation
> chore(error-responses): add links to spring documentation

- api-guidelines/async/contract/asyncapi/rules/must-provide-api-specification-using-asyncapi-for-asyncrhonous-apis.md
Changelog:
- Changed the required API description format for asynchronous APIs from `2.3.0` to `3.0.0` in "MUST provide API specification using AsyncAPI for asynchronous APIs" [R200005](https://api.otto.de/portal/guidelines/r200005).
- Extended "MUST provide API specification using AsyncAPI for asynchronous APIs" [R200005](https://api.otto.de/portal/guidelines/r200005) by the information that asynchronous APIs must be published in our internal developer portal.
> fix(rule): update async api rule

- changes/changelog.md
Fixes E2E tests and adds more context for links.
I don't know why there are so many "changes" in this PR. All I did was changing content in lines 7-9. You can ignore the rest :)
> docs(changelog): fix broken links

- src/linting/rules/define-permissions-with-scope.spec.ts
- src/linting/rules/define-permissions-with-scope.ts
- src/linting/rules/use-authorization-grant.spec.ts
- src/linting/rules/use-authorization-grant.ts
- src/vitest.config.ts
Makes our linter rules more resilient to missing "flows" properties in the securitySchemes components of OpenAPI specifications.
fixes #92
> fix(linter-rules): Handle missing flows property in OpenAPI securitySchemes
